# Structure BTP par défaut : Unités d'Œuvre + Tâches créées automatiquement
# à chaque nouveau chantier. Les quantités (prévue / réalisée) démarrent à 0
# et sont renseignées ensuite dans l'application.
#
# Format : (nom_UO, [(nom_tache, unite), ...])

CHANTIER_TEMPLATE = [
    ("Installation de chantier", [
        ("Reconnaissance du site", "Site"),
        ("Installation base-vie", "lieu"),
        ("Clôtures et accès", "ml"),
        ("Réseaux provisoires", "localisation"),
        ("Signalisation sécurité", "localisation"),
        ("Débroussaillage", "ha"),
        ("Décapage terre végétale", "m³"),
    ]),
    ("Préparation et terrassements", [
        ("Reconnaissance topographique", "levé"),
        ("Implantation axes", "axe"),
        ("Décapage plateforme", "m²"),
        ("Terrassement pleine masse/excavation", "m³"),
        ("Fouilles rigoles/Tranchée", "m³"),
        ("Réglage fond de fouille", "m²"),
        ("Compactage plateformes", "m²"),
        ("Remblaiement", "m³"),
    ]),
    ("Fondations", [
        ("Béton de propreté", "m³"),
        ("Ferraillage semelles", "t"),
        ("Coffrage semelles", "m²"),
        ("Bétonnage semelles", "m³"),
        ("Réalisation longrines", "ml"),
        ("Murs de soubassement", "m²"),
        ("Dallage/radier", "m²"),
        ("Étanchéité enterrée", "m²"),
        ("Drainage périphérique", "ml"),
    ]),
    ("Gros œuvre", [
        ("Poteaux en béton armé", "unité"),
        ("Voiles porteurs", "m²"),
        ("Élévation maçonnerie", "m³"),
        ("Chaînages verticaux", "ml"),
        ("Chaînages horizontaux", "ml"),
        ("Linteaux", "ml"),
        ("Poutres béton armé", "ml"),
        ("Ferraillage poutres", "t"),
        ("Coffrage poutres", "m²"),
        ("Planchers béton armé", "m²"),
        ("Étaiement/désétaiement", "m²"),
    ]),
    ("Charpente et couverture", [
        ("Fabrication charpente", "t"),
        ("Levage et pose charpente", "t"),
        ("Traitement bois", "t"),
        ("Pose éléments couverture", "m²"),
        ("Isolation toiture", "m²"),
        ("Étanchéité toiture", "m²"),
        ("Évacuation eaux pluviales", "ml"),
        ("Gouttières et descentes", "ml"),
    ]),
    ("Façades et menuiseries", [
        ("Enduits extérieurs", "m²"),
        ("ITE (Isolation Thermique)", "m²"),
        ("Pose fenêtres", "unité"),
        ("Pose portes extérieures", "unité"),
        ("Vitrages", "m²"),
        ("Calfeutrement étanchéité", "ml"),
    ]),
    ("Plomberie et CVC", [
        ("Réseaux alimentation eau", "ml"),
        ("Réseaux évacuation EU/EV", "ml"),
        ("Réseaux eaux pluviales", "ml"),
        ("Pose appareils sanitaires", "unité"),
        ("Réseaux chauffage", "ml"),
        ("Réseaux ventilation", "ml"),
        ("Installation climatisation", "unité"),
        ("Équipements techniques", "unité"),
    ]),
    ("Électricité et sécurité", [
        ("Réservations et gaines", "ml"),
        ("Tirage câbles", "km"),
        ("Tableaux électriques", "unité"),
        ("Appareillages", "unité"),
        ("Éclairage intérieur", "unité"),
        ("Éclairage extérieur", "unité"),
        ("Mise à la terre", "ml"),
        ("Détection incendie", "unité"),
        ("Éclairage de sécurité", "unité"),
        ("Signalisation sécurité", "unité"),
    ]),
    ("Second œuvre", [
        ("Cloisons traçage", "m²"),
        ("Ossatures cloisons", "ml"),
        ("Isolants cloisons", "m²"),
        ("Plaques de plâtre", "m²"),
        ("Traitement joints", "ml"),
        ("Doublages", "m²"),
        ("Chapes", "m³"),
        ("Ragréage", "m²"),
    ]),
    ("Revêtements", [
        ("Carrelage sols", "m²"),
        ("Carrelage murs", "m²"),
        ("Revêtements souples", "m²"),
        ("Parquet", "m²"),
        ("Plinthes", "ml"),
        ("Peinture murs", "m²"),
        ("Peinture plafonds", "m²"),
        ("Faux plafonds", "m²"),
    ]),
    ("Menuiseries intérieures", [
        ("Blocs-portes", "unité"),
        ("Portes intérieures", "unité"),
        ("Habillages", "ml"),
        ("Escaliers", "unité"),
        ("Garde-corps", "ml"),
        ("Mobiliers fixes", "unité"),
    ]),
    ("Aménagements extérieurs", [
        ("Terrassements VRD", "m³"),
        ("Assainissement EU/EV", "ml"),
        ("Réseau eau potable ext", "ml"),
        ("Réseaux électriques ext", "ml"),
        ("Regards et caniveaux", "unité"),
        ("Voiries et cheminements", "m²"),
        ("Couches de chaussée", "m³"),
        ("Bordures", "ml"),
        ("Trottoirs", "m²"),
        ("Parkings", "m²"),
        ("Éclairage extérieur", "unité"),
        ("Clôtures et portails", "ml"),
        ("Espaces verts", "m²"),
    ]),
    ("Équipements et finitions", [
        ("Équipements sanitaires", "unité"),
        ("Équipements électriques", "unité"),
        ("Équipements cuisine", "unité"),
        ("Signalétique", "unité"),
    ]),
    ("Essais et réception", [
        ("Tests hydrauliques", "réseau"),
        ("Tests électriques", "circuit"),
        ("Tests CVC", "système"),
        ("Tests équipements", "équipement"),
        ("Nettoyage fin de chantier", "m²"),
        ("Levée des réserves", "réserve"),
        ("Réception travaux", "chantier"),
    ]),
]
